// Company Name...............................SAES
// File Name..................................panel1


/**
 * @file panel1.h
 * @brief Defines the type panel1Gw as panel1.
 * @details This file was generated by codeGenerator.
 */

#ifndef __PANEL1_H__
#define __PANEL1_H__

#pragma once

#include "panel1Gw.h"

/**
 * @brief Defines the type panel1Gw as panel1.
 */
typedef panel1Gw panel1;

#endif  // __PANEL1_H__