// Company Name...............................SAES
// File Name..................................panel1

/**
 * @file panel1Gw.h
 * @brief Header for the class panel1Gw.
 * @details This file was generated by codeGenerator.
 */

#ifndef __PANEL1GW_H__
#define __PANEL1GW_H__

#pragma once

#include "panel1QtCb.h"

/**
 * @class panel1Gw
 * @brief Clase que hereda de panel1QtCb, representa un panel con funcionalidad específica.
 */
class panel1Gw : public panel1QtCb
{
public:
    /**
     * @brief Constructor de la clase panel1Gw.
     * @param parent Puntero al objeto BaseClass padre (nullptr por defecto).
     */
    panel1Gw(BaseClass* parent = 0);
    /**
     * @brief Destructor de la clase panel1Gw.
     */
    virtual ~panel1Gw();

protected:
    /**
     * @brief Info del método exportGetParameterLimit()
     * @return devuelve un puntero a un objeto de tipo ParameterLimitData
    */
    virtual const ParameterLimitData* exportGetParameterLimit()override final;
    /**
     * @brief Info del método exportAction()
    */
    virtual void exportAction(const Common::Action& , const boost::any&)override final;
    /**
     * @brief Info del método exportMessage()
    */
    virtual void exportMessage(const Format::MessageKind&, const Format::MessageBody&)override final;    
};

#endif  // __PANEL1GW_H__
