// Company Name...............................SAES
// File Name..................................panel1

/**
 * @file panel1Gw.cpp
 * @brief Implements panel1Gw.
 * @details This file was generated by codeGenerator.
 */

#include "panel1Gw.h"



panel1Gw::panel1Gw(BaseClass * parent)
: panel1QtCb(parent)
{

}

panel1Gw::~panel1Gw()
{

}
//------------------------------------------------------------------------------------
/*virtual*/ const ParameterLimitData* panel1Gw::exportGetParameterLimit()
{
    return ConfigSignals::ParameterLimit_get().value_or(nullptr);
}
//-----------------------------------------------------------------------------------------
void panel1Gw::exportAction(const Common::Action& p_action, const boost::any& p_any)
{
    //ControllerSignals::Action_cmd_id(p_action, p_any);
}
//-----------------------------------------------------------------------------------------
void panel1Gw::exportMessage(const Format::MessageKind& p_kind, const Format::MessageBody& p_body)
{
    //ControllerSignals::Message_cmd_id(p_kind, p_body);
}
//------------------------------------------------------------------------------------
