// Company Name...............................SAES
// File Name..................................panel1

/**
 * @file panel1QtCb.cpp
 * @brief Implements panel1QtCb.
 * @details This file was generated by codeGenerator.
 */

#include "panel1QtCb.h"
#include "ui_panel1.h"


#include <QRegularExpression>
#include <QRegularExpressionValidator>



class panel1QtCb::PrivateData
{
    public:
        /**
         * @brief Constructor de la clase PrivateData.
         * @param parent Puntero al objeto BaseClass padre (nullptr por defecto).
         */
        PrivateData(BaseClass* parent)
        {

        }
        /**
         * @brief Destructor de la clase PrivateData.
         */
        ~PrivateData()
        {}      
        /**
         * UI del panel
         */
        Ui::panel1 ui;
};


panel1QtCb::panel1QtCb(BaseClass * parent)
    : BaseClass(parent)
    , p_impl(new PrivateData(parent))
{
    p_impl->ui.setupUi(this);

    initialize();

    signalsAndSlots();

}

panel1QtCb::~panel1QtCb()
{

}
//----------------------------------------------------------------
void panel1QtCb::init()
{
    const ParameterLimitData* limit = exportGetParameterLimit();
    if(limit)
    {

    }
}
//----------------------------------------------------------------
void panel1QtCb::initialize()
{   
    addFooterButton(Footer::Button_Apply, p_impl->ui.pbApply);

    addFooterButton(Footer::Button_Cancel, p_impl->ui.pbCancel);

    
    addFooterButton(Footer::Button_Reset, p_impl->ui.pbReset);

    addFooterButton(Footer::Button_Custom_1, p_impl->ui.botonCustom);

    

    addComponents(p_impl->ui.generatedLayout);
}

//----------------------------------------------------------------
void panel1QtCb::signalsAndSlots()
{

}


//----------------------------------------------------------------
void panel1QtCb::panelApply()
{
	// Implementation here
}

//----------------------------------------------------------------
void panel1QtCb::panelCancel()
{
	// Implementation here
}

//----------------------------------------------------------------
void panel1QtCb::panelReset()
{
	// Implementation here
}

//----------------------------------------------------------------
void panel1QtCb::panelCustom1()
{
	// Implementation here
}


//--------------------------------------------------------------------------------------------

